apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Address
metadata:
  name: eip-${{ values.clusterName }}
spec:
  providerConfigRef:
    name: default
  forProvider:
    region: ${{ values.region }}
    vpc: true