apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: private-rt-${{ values.clusterName }}
spec:
  providerConfigRef:
    name: default
  forProvider:
    region: ${{ values.region }}
    vpcIdRef:
      name: vpc-${{ values.clusterName }}
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: public-rt-${{ values.clusterName }}
spec:
  providerConfigRef:
    name: default
  forProvider:
    region: ${{ values.region }}   
    vpcIdRef:
      name: vpc-${{ values.clusterName }}
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Route
metadata:
  name: private-route-${{ values.clusterName }}
spec:
  providerConfigRef:
    name: default
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    natGatewayIdRef:
      name: nat-${{ values.clusterName }}
    region: ${{ values.region }}
    routeTableIdRef:
      name: private-rt-${{ values.clusterName }}
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Route
metadata:
  name: public-route-${{ values.clusterName }}
spec:
  providerConfigRef:
    name: default
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    gatewayIdRef:
      name: igw-${{ values.clusterName }}
    region: ${{ values.region }}
    routeTableIdRef:
      name: public-rt-${{ values.clusterName }}
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: private-rta-${{ values.clusterName }}
spec:
  providerConfigRef:
    name: default
  forProvider:
    region: ${{ values.region }}
    routeTableIdRef:
      name: private-rt-${{ values.clusterName }}
    subnetIdRef:
      name: private-subnet-${{ values.region }}-a
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: public-rta-${{ values.clusterName }}
spec:
  providerConfigRef:
    name: default
  forProvider:
    region: ${{ values.region }}
    routeTableIdRef:
      name: public-rt-${{ values.clusterName }}
    subnetIdRef:
      name: public-subnet-${{ values.region }}-b