apiVersion: v1
kind: Service
metadata:
  name: ${{ values.backendName }}-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: ${{ values.backendName }}-deployment
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000