apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: vpc-${{ values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  providerConfigRef:
    name: aws-provider-config
  forProvider:
    region: ${{ values.region }}
    cidrBlock: 10.0.0.0/16
    enableDnsHostnames: true
    enableDnsSupport: true