export const RETURNING_REQUEST_STATE = {
  WAITING_FOR_RETURNING: 1,
  COMPLETED: 2,
};

export const RETURNING_REQUEST_STATE_NAME = {
  [RETURNING_REQUEST_STATE.WAITING_FOR_RETURNING]: "Waiting for returning",
  [RETURNING_REQUEST_STATE.COMPLETED]: "Completed",
};

export const RETURNING_REQUEST_STATE_OPTIONS = [
  {
    value: RETURNING_REQUEST_STATE.WAITING_FOR_RETURNING,
    name: RETURNING_REQUEST_STATE_NAME[RETURNING_REQUEST_STATE.WAITING_FOR_RETURNING],
  },
  {
    value: RETURNING_REQUEST_STATE.COMPLETED,
    name: RETURNING_REQUEST_STATE_NAME[RETURNING_REQUEST_STATE.COMPLETED],
  },
];