apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: eks-cluster
  title: New ESK Cluster
  description: An  template for the scaffolder that provision a EKS cluster using Crossplane and ArgoCD
  tags: 
    - infrastructure
spec:
  owner: user:le.caothihoang
  type: infrastructure

  parameters:  
    - title: Choose a Repo location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location for ArgoCD to Deploy
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                github:
                - repo  # Allows creating repositories
                - workflow  # Allows managing GitHub Actions
                azure:
                - email
                - openid
            allowedHosts:
              - github.com
              - dev.azure.com
    - title: Basic EKS Cluster Configuration
      required:
        - clusterName
        - region
      properties:
        clusterName:
          title: EKS Cluster Name
          type: string
          description: The name of the EKS cluster to create
          ui:autofocus: true
        region:
          title: Region
          type: string
          description: The region where the EKS cluster will be deployed
          enum:
            - us-east-1
            - us-east-2
            - us-west-1
            - us-west-2
            - ap-east-1
            - ap-south-2
            - ap-south-1
            - ap-northeast-3
        customKyvernoPolicies:
          title: Custom Policy Repository Location
          type: string
          description: The source repository of the custome Kyverno policies specific to the cluster
  steps:
    - id: validate-github-token
      name: Validate Token
      action: custom:get-secret
      input:
        secretKey: PORTAL_SECRET_GITHUB_TOKEN
    - id: fetch-base-eks-skeleton
      name: Fetch EKS Cluster skeleton
      action: fetch:template
      input:
        url: ./content
        values:
          clusterName: ${{ parameters.clusterName }}
          region: ${{ parameters.region }}                 
          owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner')}} 
          repo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo')}} 
    
    # This step publishes to Azure DevOps
    - id: publish
      name: Publish to Github
      if: ${{ parameters.repoUrl | parseRepoUrl | pick('host') === "github.com" }}
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.clusterName }}
        repoUrl: ${{ parameters.repoUrl }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}

    # This step publishes to Azure DevOps
    - id: publish
      name: Publish to Azure DevOps
      if: ${{ parameters.repoUrl | parseRepoUrl | pick('host') === "dev.azure.com" }}
      action: publish:azure
      input:
        allowedHosts: ['dev.azure.com']
        description: This is ${{ parameters.clusterName }}
        repoUrl: ${{ parameters.repoUrl }}
        organization: ${{ parameters.repoUrl | parseRepoUrl | pick('organization') }}
        project: ${{ parameters.repoUrl | parseRepoUrl | pick('project') }}
        repo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}


    - id: github-action
      name: Trigger GitHub Action for github host
      if: ${{ parameters.repoUrl | parseRepoUrl | pick('host') === "github.com" }}
      action: github:actions:dispatch
      input:
        workflowId: deploy_eks_with_argocd.yaml
        repoUrl: 'github.com?owner=nashtech-garage&repo=self-service-portal'
        branchOrTagName: 'main'
        token:  ${{ steps['validate-github-token'].output.value }}
        workflowInputs:
          clusterName: ${{ parameters.clusterName }}
          region: ${{ parameters.region }}    
          repoURLforArgo: ${{ steps['publish'].output.remoteUrl }} 
          host: ${{ parameters.repoUrl | parseRepoUrl | pick('host') }}
          customKyvernoPolicies: ${{ parameters.customKyvernoPolicies }}
          username: ${{ parameters.repoUrl | parseRepoUrl | pick('owner')}} 
          repoURLToken: ${{ secrets.USER_OAUTH_TOKEN }}

    - id: github-action
      name: Trigger GitHub Action for azure host
      if: ${{ parameters.repoUrl | parseRepoUrl | pick('host') === "dev.azure.com" }}
      action: github:actions:dispatch
      input:
        workflowId: deploy_aks_with_argocd.yaml
        repoUrl: 'github.com?owner=nashtech-garage&repo=self-service-portal'
        token:  ${{ steps['validate-github-token'].output.value }}
        branchOrTagName: 'main'
        workflowInputs:
          clusterName: ${{ parameters.clusterName }}
          region: ${{ parameters.region }}
          resourceGroupName: ${{ parameters.resourceGroupName }}
          kubernetesVersion: ${{ parameters.kubernetesVersion}}
          dnsPrefix: ${{ parameters.dnsPrefix }}          
          repoURLforArgo: ${{ steps['publish'].output.remoteUrl }} 
          host: ${{ parameters.repoUrl | parseRepoUrl | pick('host') }}
          username: ${{ parameters.repoUrl | parseRepoUrl | pick('organization')}} 
          repoURLToken: ${{ secrets.USER_OAUTH_TOKEN }}


  output:
    links:
      - title: A new repository created
        url: ${{ steps['publish'].output.remoteUrl }}