apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: stepone-eks
spec:
  forProvider:
    region: ap-southeast-2
    roleArnSelector:
      matchControllerRef: true
      matchLabels:
        role-name: stepone-eks-role
    version: "1.29"
    resourcesVpcConfig:
      subnetIdSelector:
        matchControllerRef: true
        matchLabels:
          vpc-name: stepone-vpc
      endpointPublicAccess: true
      endpointPrivateAccess: true
  providerConfigRef:
    name: default

---
apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: stepone-node-group
spec:
  forProvider:
    region: up-southeast-2
    clusterNameRef:
      name: stepone-eks
    nodeRoleArnSelector:
      matchControllerRef: true
      matchLabels:
        role-name: stepone-eks-role
    subnetIdSelector:
      matchControllerRef: true
      matchLabels:
        vpc-name: stepone-vpc
    instanceTypes:
      - t3.medium
    scalingConfig:
      minSize: 1
      maxSize: 3
      desiredSize: 2
  providerConfigRef:
    name: default