apiVersion: eks.aws.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: stepone-eks
spec:
  forProvider:
    region: ap-southeast-2
    roleArnRef:
      name: eks-cluster-role
    resourcesVpcConfig:
      subnetIdRefs:  # Sử dụng subnetIdRefs để tham chiếu đến các Subnet
        - name: private-subnet-a  # Tên của Subnet trong subnet.yaml
        - name: private-subnet-b
  providerConfigRef:
    name: aws-provider

---
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: stepone-node-group
spec:
  forProvider:
    region: ap-southeast-2
    clusterName: stepone-eks
    nodeRoleArnRef:
      name: eks-node-role
    scalingConfig:
      minSize: 1
      maxSize: 2
      desiredSize: 1
  providerConfigRef:
    name: aws-provider