apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: ${{ values.clusterName }}
spec:
  forProvider:
    region: ${{ values.region }}
    roleArnRef:
      name: eks-cluster-role
    resourcesVpcConfig:
      subnetIdRefs:
        - name: private-subnet-${{ values.region }}a
        - name: public-subnet-${{ values.region }}b
  providerConfigRef:
    name: default

---
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: nodegroup-${{ values.clusterName }}
spec:
  forProvider:
    region: ${{ values.region }}
    clusterNameRef:
      name: ${{ values.clusterName }}
    nodeRoleArnRef:
      name: ex-eks-nodes-role
    scalingConfig:
      minSize: 1
      maxSize: 2
      desiredSize: 1
    capacityType: ON_DEMAND
    instanceTypes: ["t3.medium"]
    diskSize: 20
    subnetIdRefs:
      - name: private-subnet-${{ values.region }}a
      - name: public-subnet-${{ values.region }}b
  providerConfigRef:
    name: default