apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: stepone-eks
spec:
  forProvider:
    region: ap-southeast-2
    roleArnRef:
      name: eks-cluster-role
    resourcesVpcConfig:
      subnetIdRefs:
        - name: private-subnet-a
        - name: private-subnet-b
  providerConfigRef:
    name: default

---
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: stepone-node-group
spec:
  forProvider:
    region: ap-southeast-2
    clusterName: stepone-eks
    clusterNameRef:
      name: eks-node-role
    scalingConfig:
      minSize: 1
      maxSize: 2
      desiredSize: 1
  providerConfigRef:
    name: default