apiVersion: cache.elasticache.aws.upbound.io/v1beta1
kind: SubnetGroup
metadata:
  name: stepone-elasticache-subnet-group
spec:
  forProvider:
    region: ap-southeast-2
    description: Subnet group for stepone ElastiCache
    subnetIdSelector:
      matchControllerRef: true
      matchLabels:
        vpc-name: stepone-vpc
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: stepone-elasticache-sg
spec:
  forProvider:
    region: ap-southeast-2
    vpcIdSelector:
      matchControllerRef: true
    description: Security group for stepone ElastiCache
    ingress:
      - fromPort: 6379
        toPort: 6379
        protocol: tcp
        cidrBlocks:
          - 10.0.0.0/16  # Allows traffic from within the VPC
  providerConfigRef:
    name: default
---
apiVersion: cache.elasticache.aws.upbound.io/v1beta1
kind: CacheCluster
metadata:
  name: stepone-elasticache
spec:
  forProvider:
    region: ap-southeast-2
    engine: redis
    engineVersion: "7.0"
    nodeType: cache.t3.micro
    numCacheNodes: 1
    cacheSubnetGroupNameSelector:
      matchControllerRef: true
    securityGroupIdSelector:
      matchControllerRef: true
      matchLabels:
        sg-name: stepone-elasticache-sg
  providerConfigRef:
    name: default