apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: stepone-eks-role
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
  providerConfigRef:
    name: default

---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: stepone-eks-role-policy
spec:
  forProvider:
    roleNameRef:
      name: stepone-eks-role
    policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  providerConfigRef:
    name: default

