apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  name: my-eks-igw
spec:
  forProvider:
    region: ap-southeast-2
    vpcIdRef:
      name: my-eks-vpc
  providerConfigRef:
    name: aws-provider
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: NatGateway
metadata:
  name: my-eks-natgw
spec:
  forProvider:
    region: ap-southeast-2
    subnetIdRef:
      name: public-subnet  # You need a public subnet for the NAT Gateway
  providerConfigRef:
    name: aws-provider
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: private-subnet-route
spec:
  forProvider:
    region: ap-southeast-2
    vpcIdRef:
      name: my-eks-vpc
  providerConfigRef:
    name: aws-provider
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Route
metadata:
  name: nat-route
spec:
  forProvider:
    region: ap-southeast-2
    routeTableIdRef:
      name: private-subnet-route
    destinationCidrBlock: 0.0.0.0/0
    natGatewayIdRef:
      name: my-eks-natgw
  providerConfigRef:
    name: aws-provider




