apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: public-subnet-a
  labels:
    vpc-name: stepone-vpc
    subnet-type: public
spec:
  forProvider:
    region: ap-southeast-2
    vpcIdSelector:
      matchControllerRef: true
    cidrBlock: 10.0.3.0/24
    availabilityZone: us-east-1a
    mapPublicIpOnLaunch: true
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: stepone-igw
spec:
  forProvider:
    region: us-east-1
    vpcIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: stepone-public-rt
spec:
  forProvider:
    region: ap-southeast-2
    vpcIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Route
metadata:
  name: stepone-public-route
spec:
  forProvider:
    region: ap-southeast-2
    routeTableIdSelector:
      matchControllerRef: true
      matchLabels:
        rt-type: public
    destinationCidrBlock: 0.0.0.0/0
    gatewayIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: stepone-public-rt-association
spec:
  forProvider:
    region: ap-southeast-2
    subnetIdSelector:
      matchLabels:
        subnet-type: public
    routeTableIdSelector:
      matchControllerRef: true
      matchLabels:
        rt-type: public
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: stepone-private-rt
spec:
  forProvider:
    region: ap-southeast-2
    vpcIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: default