apiVersion: rds.aws.crossplane.io/v1beta1
kind: DBSubnetGroup
metadata:
  name: my-rds-subnet-group
spec:
  forProvider:
    region: ap-southeast-2
    description: "Subnet group for private RDS"
    subnetIdRefs: 
      - name: private-subnet-a
      - name: private-subnet-b
  providerConfigRef:
    name: aws-provider
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: rds-security-group
spec:
  forProvider:
    region: ap-southeast-2
    vpcIdRef:
      name: my-eks-vpc
    description: "Allow EKS nodes to connect to RDS"
  providerConfigRef:
    name: aws-provider
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: rds-ingress-rule
spec:
  forProvider:
    region: ap-southeast-2
    securityGroupIdRef:
      name: rds-security-group
    type: ingress
    protocol: tcp
    fromPort: 5432
    toPort: 5432
    sourceSecurityGroupIdRef:
      name: eks-node-security-group
  providerConfigRef:
    name: aws-provider
---
apiVersion: rds.aws.crossplane.io/v1beta1
kind: DBInstance
metadata:
  name: my-private-rds
spec:
  forProvider:
    region: ap-southeast-2
    dbInstanceClass: db.t3.medium
    allocatedStorage: 20
    engine: postgres
    engineVersion: "16"
    masterUsername: admin
    masterUserPasswordSecretRef:
      namespace: crossplane-system
      name: my-rds-secret
      key: password
    publiclyAccessible: false
    vpcSecurityGroupIds:
      - rds-security-group
    dbSubnetGroupNameRef:
      name: my-rds-subnet-group
  providerConfigRef:
    name: aws-provider
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: eks-to-rds
spec:
  forProvider:
    region: ap-southeast-2
    securityGroupIdRef:
      name: eks-node-security-group
    type: egress
    protocol: tcp
    fromPort: 5432
    toPort: 5432
    destinationSecurityGroupIdRef:
      name: rds-security-group
  providerConfigRef:
    name: aws-provider
---
apiVersion: secretsmanager.aws.crossplane.io/v1beta1
kind: Secret
metadata:
  name: my-rds-secret
spec:
  forProvider:
    region: ap-southeast-2
    name: my-db-secret
    secretString: |
      {
        "username": "admin",
        "password": "MyStrongPassword"
      }
  providerConfigRef:
    name: aws-provider