apiVersion: rds.aws.crossplane.io/v1beta1
kind: DBSubnetGroup
metadata:
  name: my-rds-subnet-group
spec:
  forProvider:
    region: us-east-1
    description: "Subnet group for private RDS"
    subnetIds:
      - private-subnet-a
      - private-subnet-b
  providerConfigRef:
    name: aws-provider
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: rds-security-group
spec:
  forProvider:
    region: us-east-1
    vpcIdRef:
      name: my-eks-vpc
    description: "Allow EKS nodes to connect to RDS"
  providerConfigRef:
    name: aws-provider
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: rds-ingress-rule
spec:
  forProvider:
    region: us-east-1
    securityGroupIdRef:
      name: rds-security-group
    type: ingress
    protocol: tcp
    fromPort: 5432  # PostgreSQL (Use 3306 for MySQL)
    toPort: 5432
    sourceSecurityGroupIdRef:
      name: eks-node-security-group  # Allow EKS nodes to connect
  providerConfigRef:
    name: aws-provider
---
apiVersion: rds.aws.crossplane.io/v1beta1
kind: DBInstance
metadata:
  name: my-private-rds
spec:
  forProvider:
    region: us-east-1
    dbInstanceClass: db.t3.medium  # Choose instance size
    allocatedStorage: 20
    engine: postgres
    engineVersion: "16"  # Change to "8.0" for MySQL
    masterUsername: admin
    masterUserPasswordSecretRef:
      namespace: crossplane-system
      name: my-rds-secret
      key: password
    publiclyAccessible: false  # Ensures private subnet usage
    vpcSecurityGroupIds:
      - rds-security-group
    dbSubnetGroupNameRef:
      name: my-rds-subnet-group
  providerConfigRef:
    name: aws-provider
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: eks-to-rds
spec:
  forProvider:
    region: us-east-1
    securityGroupIdRef:
      name: eks-node-security-group
    type: egress
    protocol: tcp
    fromPort: 5432
    toPort: 5432
    destinationSecurityGroupIdRef:
      name: rds-security-group
  providerConfigRef:
    name: aws-provider
---
apiVersion: secretsmanager.aws.crossplane.io/v1beta1
kind: Secret
metadata:
  name: my-rds-secret
spec:
  forProvider:
    region: us-east-1
    name: my-db-secret
    secretString: |
      {
        "username": "admin",
        "password": "MyStrongPassword"
      }
  providerConfigRef:
    name: aws-provider



