apiVersion: database.aws.crossplane.io/v1beta1
kind: DBSubnetGroup
metadata:
  name: my-rds-subnet-group
spec:
  forProvider:
    region: ap-southeast-2
    description: "Subnet group for private RDS"
    subnetIdRefs: 
      - name: private-subnet-a
      - name: private-subnet-b
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: rds-security-group
spec:
  forProvider:
    groupName: rds-sg
    region: ap-southeast-2
    vpcIdRef:
      name: stepone-vpc
    description: "Allow EKS nodes to connect to RDS"
    tags:
      - key: Name
        value: sg-rds
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  name: rds-ingress-rule
spec:
  forProvider:
    region: ap-southeast-2
    securityGroupIdRef:
      name: rds-security-group
    type: ingress
    protocol: tcp
    fromPort: 5432
    toPort: 5432
    cidrBlock: 10.0.0.0/16
  providerConfigRef:
    name: default
---
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: my-private-rds
spec:
  forProvider:
    region: ap-southeast-2
    dbInstanceClass: db.t3.medium
    allocatedStorage: 20
    engine: postgres
    engineVersion: "16"
    masterUsername: root
    masterUserPasswordSecretRef:
      namespace: crossplane-system
      name: rds-password
      key: password
    publiclyAccessible: false
    vpcSecurityGroupIDRefs:
      - name: rds-security-group
    dbSubnetGroupNameRef:
      name: my-rds-subnet-group
  providerConfigRef:
    name: default
---
apiVersion: secretsmanager.aws.crossplane.io/v1beta1
kind: Secret
metadata:
  name: rds-password
spec:
  forProvider:
    region: ap-southeast-2
    stringSecretRef:
      key: password
      name: rds-password
      namespace: crossplane-system
  providerConfigRef:
    name: default
