apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: infra-stepone
spec:
  forProvider:
    locationConstraint: ap-southeast-2
    acl: private
  providerConfigRef:
    name: aws-provider
