apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: private-subnet-a
spec:
  forProvider:
    region: ap-southeast-2
    vpcIdRef:
      name: stepone-vpc
    cidrBlock: 10.0.1.0/24
    availabilityZone: ap-southeast-2a
    mapPublicIPOnLaunch: false
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: private-subnet-b
spec:
  forProvider:
    region: ap-southeast-2
    vpcIdRef:
      name: stepone-vpc
    cidrBlock: 10.0.2.0/24
    availabilityZone: ap-southeast-2b
    mapPublicIPOnLaunch: false
  providerConfigRef:
    name: default