apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: private-subnet-a
spec:
  forProvider:
    region: ap-southeast-2
    vpcIdSelector:
      matchLabels:
        vpc-name: stepone-vpc
    cidrBlock: 10.0.1.0/24
    availabilityZone: ap-southeast-2a
    mapPublicIpOnLaunch: false
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: private-subnet-b
spec:
  forProvider:
    region: ap-southeast-2
    vpcIdSelector:
      matchLabels:
        vpc-name: stepone-vpc
    cidrBlock: 10.0.2.0/24
    availabilityZone: ap-southeast-2b
    mapPublicIpOnLaunch: false
  providerConfigRef:
    name: default
