apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: vpc-${{ values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  forProvider:
    region: ${{ values.region }}
    cidrBlock: ${{ values.cidrVPCBlock }}
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
  providerConfigRef:
    name: default