apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: my-eks-vpc
spec:
  forProvider:
    region: us-east-1
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
    enableDnsHostnames: true
  providerConfigRef:
    name: aws-provider
