apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: stepone-vpc
spec:
  forProvider:
    region: ap-southeast-2
    cidrBlock: 10.0.0.0/16
    enableDnsHostnames: true
    enableDnsSupport: true
  providerConfigRef:
    name: default