parameters:
  - name: source
    type: string
  - name: scanCode
    type: boolean
    default: false
  - name: scanImage
    type: boolean
    default: false
  - name: serviceConnectionEndpoint
    type: string
jobs:
  - job: snykScanCode
    displayName: Snyk Scan Code
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      {% raw %}- checkout: ${{ parameters.source }}{% endraw %}
      - task: SnykSecurityScan@1
        inputs:
          {% raw %}serviceConnectionEndpoint: ${{ parameters.serviceConnectionEndpoint }}{% endraw %}
          testType: 'code'
          failOnIssues: $(failOnIssues)
          projectName: $(projectName)
          organization: $(organization)
          additionalArguments: $(additionalArguments)
