parameters:
  - name: source
    type: string
  - name: SonarQube
    type: string
  - name: jdkVersion
    type: string
    default: 17
jobs:
  - job: sonarScan
    displayName: SonarQube Scan
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: {% raw %}${{ parameters.source }}{% endraw %}
      - task: JavaToolInstaller@1
        inputs:
          versionSpec: {% raw %}'${{ parameters.jdkVersion }}'{% endraw %}
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
        displayName: {% raw %}'Use Java ${{ parameters.jdkVersion }}'{% endraw %}
      {%- if values.parameters.sonarConfig.sonarHost == 'Cloud' %}
      - task: SonarCloudPrepare@3
        inputs:
          SonarQube: {% raw %}${{ parameters.SonarQube}}{% endraw %}
          scannerMode: dotnet
          dotnetScannerVersion: $(dotnetScannerVersion)
          configMode: $(configMode)
          projectKey: $(projectKey)
          projectName: $(projectName)
          extraProperties: $(extraProperties)
          organization: $(organization)
      {%- else %}
      - task: SonarQubePrepare@7
        inputs:
          SonarQube: {% raw %}${{ parameters.SonarQube}}{% endraw %}
          scannerMode: 'dotnet'
          dotnetScannerVersion: $(dotnetScannerVersion)
          configMode: $(configMode)
          projectKey: $(projectKey)
          projectName: $(projectName)
          extraProperties: $(extraProperties)
      {%- endif %}
      - task: DotNetCoreCLI@2
        displayName: 'Build'
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--configuration Release'
      {%- if values.parameters.sonarConfig.sonarHost == 'Cloud' %}
      - task: SonarCloudAnalyze@3
        inputs:
          jdkversion: {% raw %}${{ parameters.jdkVersion }}{% endraw%}
      - task: SonarCloudPublish@3
        inputs:
          pollingTimeoutSec: '300'
      {%- else %}
      - task: SonarQubeAnalyze@7
        inputs:
          jdkversion: {% raw %}${{ parameters.jdkVersion }}{% endraw%}
      - task: SonarQubePublish@7
        inputs:
          pollingTimeoutSec: '300'
      {% endif %}

