parameters:
  - name: source
    type: string

jobs:
  - job: trivyScanCode
    displayName: Trivy Scan Code
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
      {% raw %}- checkout: ${{ parameters.source }}{% endraw %}
      - task: trivy@2
        inputs:
          {%- if values.parameters.trivyCodeConfig.method == 'docker' %}
          method: $(method)
          image: $(image)
          {%- endif %}
          {%- if values.parameters.trivyCodeConfig.method == 'system' %}
          method: $(method)
          templates: $(templates)
          {%- endif %}
          version: $(version)
          options: $(options)
          type: $(type)
          target: $(target)
          scanners: $(scanners)
          severities: $(severities)
          ignoreUnfixed: $(ignoreUnfixed)
          showSuppressed: $(showSuppressed)
          ignoreScanErrors: $(ignoreScanErrors)
          failOnSeverityThreshold: $(failOnSeverityThreshold)
          reports: $(reports)
          publish: $(publish)
