apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: ${{ values.clusterName }}
spec:
  forProvider:
    region: ${{ values.region }}
    roleArnRef:
      name: eks-${{ values.clusterName }}-role
    resourcesVpcConfig:
      subnetIdRefs:
        - name: private-subnet-${{ values.clusterName }}-a
  providerConfigRef:
    name: default
