# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: back-stack
spec:
  owner: platform-engineers
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: nashtech-idp
spec:
  owner: platform-engineers
