apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: vn-${{ values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/depends-on: ${{ values.resourceGroupName }}
spec:
  providerConfigRef:
    name: azure-provider-config
  forProvider:
    resourceGroupNameRef:
      name: ${{ values.resourceGroupName }}
    location: ${{ values.region }}
    addressSpace:
      - 10.2.0.0/16
