trigger: none
parameters:
  - name: sourceAlias
    default: ${{ values.parameters.sourceRepoAlias }}
  {%- if values.parameters.frontendScan.useSnyk %}
  - name: runSnykCode
    type: boolean
    default: true
    displayName: Run Snyk Scan
  {%- endif %}
  {%- if values.parameters.frontendScan.useSonar %}
  - name: runSonarCode
    type: boolean
    default: true
    displayName: Run SonarQube Scan
  {%- endif %}
  {%- if values.parameters.frontendScan.useTrivy %}
  - name: runTrivyCode
    type: boolean
    default: true
    displayName: Run Trivy Scan
  {%- endif %}

resources:
  repositories: 
    - repository: ${{ values.parameters.sourceRepoAlias }}
      type: git
      name: ${{ values.parameters.sourceRepoName }}
      ref: ${{ values.parameters.scanBranch }}

stages:
  {%- if values.parameters.frontendScan.useSnyk 
    or values.parameters.backendScan.useSnykCode 
    or values.parameters.backendScan.useSnykDonetContainer %}
  - stage: SnykScanCode
      condition: 
      dependsOn: []
      jobs:
        - template: snyk.yaml
          parameters:
            enabled: true
            {% raw %}source: ${{ parameters.sourceAlias }}{% endraw %}
            serviceConnectionEndpoint: ${{ values.parameters.snykCodeConfig.serviceConnectionEndpoint }}
            {%- if values.parameters.frontendScan.useSnyk %}scanCode: true{%- endif %}
            {%- if values.parameters.backendScan.useSnykCode %}scanCodeBackend: true{%- endif %}
            {%- if values.parameters.backendScan.useSnykDonetContainer %}scanContainerBackend: true{%- endif %}
      variables:
        - group: ${{ values.parameters.snykCodeVariableGroupName }}   
  {%- endif %}
  {%- if values.parameters.frontendScan.useSonar 
      or values.parameters.backendScan.useSonarCode 
      or values.parameters.backendScan.useSonarContainer %}
    - stage: SonarScanCode
      dependsOn: []
      jobs:
        - template: sonar.yaml
          parameters:
            {% raw %}source: ${{ parameters.sourceAlias }}{% endraw %}
            SonarQube: ${{ values.parameters.sonarCodeConfig.SonarQube }}
            {%- if values.parameters.frontendScan.useSonar %}scanCodeSonar: true{%- endif %}
            {%- if values.parameters.backendScan.useSonarCode %}scanCodeBackendSonar: true{%- endif %}
            {%- if values.parameters.backendScan.useSonarContainer %}scanContainerBackendSonar: true{%- endif %}
      variables:
        - group: ${{ values.parameters.sonarCodeVariableGroupName }}
  {%- endif %}
  {%- if values.parameters.frontendScan.useTrivy 
      or values.parameters.backendScan.useTrivyCode 
      or values.parameters.backendScan.useTrivyContainer %}
    - stage: TrivyScanCode
      dependsOn: []
      jobs:
        - template: trivy.yaml
          parameters:
            {% raw %}source: ${{ parameters.sourceAlias }}{% endraw %}
            {%- if values.parameters.frontendScan.useTrivy %}scanCodeTrivy: true{%- endif %}
            {%- if values.parameters.backendScan.useTrivyCode %}scanCodeBackendTrivy: true{%- endif %}
            {%- if values.parameters.backendScan.useTrivyContainer %}scanContainerBackendTrivy: true{%- endif %}
      variables:
        - group: ${{ values.parameters.trivyCodeVariableGroupName }}
  {%- endif %}
