trigger: none
parameters:
  - name: sourceAlias
    default: ${{ values.parameters.sourceRepoAlias }}
  {%- if values.parameters.useSnykCode %}
  - name: runSnykCode
    type: boolean
    default: true
    displayName: Run Snyk Code Scan
  {%- endif %}
  {%- if values.parameters.useSonar %}
  - name: runSonar
    type: boolean
    default: true
    displayName: Run Sonar Scan
  {%- endif %}
  {%- if values.parameters.useTrivyCode %}
  - name: runTrivyCode
    type: boolean
    default: true
    displayName: Run Trivy Code Scan
  {%- endif %}
  {%- if values.parameters.useSnykImage %}
  - name: runSnykImage
    type: boolean
    default: true
    displayName: Scan Image with Snyk
  {%- endif %}
  {%- if values.parameters.useTrivyImage %}
  - name: runTrivyImage
    type: boolean
    default: true
    displayName: Scan Image with Trivy
  {%- endif %}

resources:
  repositories:
    - repository: ${{ values.parameters.sourceRepoAlias }}
      type: git
      name: ${{ values.parameters.sourceRepoName }}
      ref: ${{ values.parameters.scanBranch }}

stages:
  {%- if values.parameters.useSnykCode %}
  - stage: SnykScanCode
    dependsOn: []
    condition: {% raw %}${{ parameters.runSnykCode }}{% endraw %}
    jobs:
      - template: snyk.yaml
        parameters:
          {% raw %}source: ${{ parameters.sourceAlias }}{% endraw %}
          serviceConnectionEndpoint: ${{ values.parameters.snykCodeConfig.serviceConnectionEndpoint }}
    variables:
      - group: ${{ values.parameters.snykCodeVariableGroupName }}
  {%- endif %}
  {%- if values.parameters.useSonar %}
  - stage: SonarScan
    dependsOn: []
    condition: {% raw %}${{ parameters.runSonar }}{% endraw %}
    jobs:
      - template: sonar.yaml
        parameters:
          {% raw %}source: ${{ parameters.sourceAlias }}{% endraw %}
          SonarQube: ${{ values.parameters.sonarConfig.SonarQube }}
    variables:
      - group: ${{ values.parameters.sonarVariableGroupName }}
  {%- endif %}

  {%- if values.parameters.useTrivyCode %}
  - stage: TrivyScan
    dependsOn: []
    condition: {% raw %}${{ parameters.runTrivyCode }}{% endraw %}
    jobs:
      - template: trivy.yaml
        parameters:
          {% raw %}source: ${{ parameters.sourceAlias }}{% endraw %}
    variables:
      - group: ${{ values.parameters.trivyCodeVariableGroupName }}
  {%- endif %}
  {%- if values.parameters.useSnykImage %}
  - stage: SnykScanImage
    dependsOn: []
    condition: {% raw %}${{ parameters.runSnykImage }}{% endraw %}
    jobs:
      - template: snyk-image.yaml
        parameters:
          {% raw %}source: ${{ parameters.sourceAlias }}{% endraw %}
          serviceConnectionEndpoint: ${{ values.parameters.snykImageConfig.serviceConnectionEndpoint }}
    variables:
      - group: ${{ values.parameters.snykImageVariableGroupName }}
  {%- endif %}

  {%- if values.parameters.useTrivyImage %}
  - stage: TrivyImageScan
    dependsOn: []
    condition: {% raw %}${{ parameters.runTrivyImage }}{% endraw %}
    jobs:
      - template: trivy-image.yaml
        parameters:
          {% raw %}source: ${{ parameters.sourceAlias }}{% endraw %}
    variables:
      - group: ${{ values.parameters.trivyImageVariableGroupName }}
  {%- endif %}
