trigger: none

parameters:
  - name: sourceAlias
    default: ${{ values.parameters.sourceRepoAlias }}
  {%- if values.parameters.useSnykCode %}
  - name: runSnykCode
    type: boolean
    default: true
    displayName: Run Snyk Code Scan
  {%- endif %}
  {%- if values.parameters.useSonar %}
  - name: runSonar
    type: boolean
    default: true
    displayName: Run Sonar Scan
  {%- endif %}
  {%- if values.parameters.useTrivyCode %}
  - name: runTrivyCode
    type: boolean
    default: true
    displayName: Run Trivy Code Scan
  {%- endif %}
  {%- if values.parameters.useSnykImage %}
  - name: runSnykImage
    type: boolean
    default: true
    displayName: Scan Image with Snyk
  {%- endif %}
  {%- if values.parameters.useTrivyImage %}
  - name: runTrivyImage
    type: boolean
    default: true
    displayName: Scan Image with Trivy
  {%- endif %}

resources:
  repositories:
    - repository: ${{ values.parameters.sourceRepoAlias }}
      type: git
      name: ${{ values.parameters.sourceRepoName }}
      ref: ${{ values.parameters.scanBranch }}

stages:
  {%- if values.parameters.useSnykCode or values.parameters.useSnykImage %}
  - stage: SnykScanCode
    dependsOn: []
    condition: ${{ parameters.runSnykCode }}
    jobs:
      - template: snyk.yaml
        parameters:
          source: ${{ parameters.sourceAlias }}
          serviceConnectionEndpoint: ${{ values.parameters.snykCodeConfig.serviceConnectionEndpoint }}
    variables:
      - group: ${{ values.parameters.snykCodeVariableGroupName }}
  {%- endif %}

  {%- if values.parameters.useSonar %}
  - stage: SonarScan
    dependsOn: []
    condition: ${{ parameters.runSonar }}
    jobs:
      - template: sonar.yaml
        parameters:
          source: ${{ parameters.sourceAlias }}
          SonarQube: ${{ values.parameters.sonarConfig.SonarQube }}
          enabled: ${{ parameters.runSonar }}
    variables:
      - group: ${{ values.parameters.sonarVariableGroupName }}
  {%- endif %}

  {%- if values.parameters.useTrivyCode %}
  - stage: TrivyScan
    dependsOn: []
    condition: ${{ parameters.runTrivyCode }}
    jobs:
      - template: trivy.yaml
        parameters:
          source: ${{ parameters.sourceAlias }}
          {% if values.parameters.useTrivyCode %}scanCode: true{% endif %}
          {% if values.parameters.useTrivyImage %}scanImage: true{% endif %}
    variables:
      - group: ${{ values.parameters.trivyCodeVariableGroupName }}
  {%- endif %}

  {%- if values.parameters.useTrivyImage %}
  - stage: TrivyImageScan
    dependsOn: []
    condition: ${{ parameters.runTrivyImage }}
    jobs:
      - template: trivy-image.yaml
        parameters:
          source: ${{ parameters.sourceAlias }}
    variables:
      - group: ${{ values.parameters.trivyImageVariableGroupName }}
  {%- endif %}
