parameters:
  - name: sourceAlias
    default: ${{ values.parameters.sourceRepoAlias }}

  {% if values.parameters.useSnyk %}
  - name: runSnyk
    type: boolean
    default: false
    displayName: Run Snyk Scan
    description: Whether to include the Snyk security scan stage
  {% endif %}

  {% if values.parameters.useSonar %}
  - name: runSonar
    type: boolean
    default: false
    displayName: Run SonarQube Scan
    description: Whether to include the SonarQube code quality scan stage
  {% endif %}

  {% if values.parameters.useTrivy %}
  - name: runTrivy
    type: boolean
    default: false
    displayName: Run Trivy Scan
    description: Whether to include the Trivy container vulnerability scan stage
  {% endif %}

resources:
  repositories: 
    - repository: ${{ parameters.sourceAlias }}
      type: git
      name: ${{ values.parameters.sourceRepoName }}
      ref: ${{ values.parameters.scanBranch }}



stages:


{% if values.parameters.useSnyk %}
{% raw %}
  - ${{ if eq(parameters.useSnyk, true) }}:
    - stage: SnykScan
      jobs:
        - template: snyk.yaml
          parameters:
            enabled: true
            source: ${{ parameters.sourceAlias }}
      variables:
        - group: ${{ parameters.snykVariableGroup }}
        
{% endraw %}   
{% endif %}


{% if values.parameters.useSonar %}
{% raw %}
  - ${{ if eq(parameters.useSonar, true) }}:
    - stage: SonarScan
      jobs:
        - template: sonar.yaml
          parameters:
            enabled: true
            source: ${{ parameters.sourceAlias }}
      variables:
        - group: ${{ parameters.sonarVariableGroup }}

{% endraw %}
{% endif %}

{% if values.parameters.useTrivy %}
{% raw %}
  - ${{ if eq(parameters.useTrivy, true) }}:
    - stage: TrivyScan
      jobs:
        - template: trivy.yaml
          parameters:
            enabled: true
            source: ${{ parameters.sourceAlias }}
      variables:
        - group: ${{ parameters.trivyVariableGroup }}
{% endraw %}
{% endif %}
