trigger: none
parameters:
  - name: sourceAlias
    default: ${{ values.parameters.sourceRepoAlias }}
  {%- if values.parameters.useSnyk %}
  - name: runSnyk
    type: boolean
    default: true
    displayName: Run Snyk Scan
  {%- endif %}
  {%- if values.parameters.useSonar %}
  - name: runSonar
    type: boolean
    default: true
    displayName: Run SonarQube Scan
  {%- endif %}
  {%- if values.parameters.useTrivy %}
  - name: runTrivy
    type: boolean
    default: true
    displayName: Run Trivy Scan
  {%- endif %}

resources:
  repositories: 
    - repository: ${{ values.parameters.sourceRepoAlias }}
      type: git
      name: ${{ values.parameters.sourceRepoName }}
      ref: ${{ values.parameters.scanBranch }}

stages:
  {%- if values.parameters.useSnyk %}
  {% raw %}- ${{ if eq(parameters.runSnyk, true) }}:
    - stage: SnykScan
      dependsOn: []
      jobs:
        - template: snyk.yaml
          parameters:
            enabled: true
            source: ${{ parameters.sourceAlias }}{% endraw %}
            serviceConnectionEndpoint: ${{ values.parameters.snykConfig.serviceConnectionEndpoint }}
      variables:
        - group: ${{ values.parameters.snykVariableGroupName }}   
  {%- endif %}
  {%- if values.parameters.useSonar %}
  {% raw %}- ${{ if eq(parameters.runSonar, true) }}:
    - stage: SonarScan
      dependsOn: []
      jobs:
        - template: sonar.yaml
          parameters:
            enabled: true
            source: ${{ parameters.sourceAlias }}{% endraw %}
            SonarQube: ${{ values.parameters.sonarConfig.SonarQube }}
      variables:
        - group: ${{ values.parameters.sonarVariableGroupName }}
  {%- endif %}
  {%- if values.parameters.useTrivy %}
  {% raw %}- ${{ if eq(parameters.runTrivy, true) }}:
    - stage: TrivyScan
      dependsOn: []
      jobs:
        - template: trivy.yaml
          parameters:
            enabled: true
            source: ${{ parameters.sourceAlias }}{% endraw %}
      variables:
        - group: ${{ values.parameters.trivyVariableGroupName }}
  {%- endif %}
