parameters:
  job1Enabled: boolean
  job2Enabled: boolean
  job3Enabled: boolean

stages:
  - stage: RunConditionalJobs
    jobs:
      # Job 1 Template Conditional Execution
      - template: templates/job1-template.yml
        parameters:
          enabled: ${{ parameters.job1Enabled }}

      # Job 2 Template Conditional Execution
      - template: templates/job2-template.yml
        parameters:
          enabled: ${{ parameters.job2Enabled }}

      # Job 3 Template Conditional Execution
      - template: templates/job3-template.yml
        parameters:
          enabled: ${{ parameters.job3Enabled }}
