parameters:
  - name: source
      type: string
  - name: enabled
      type: boolean
      default: false

jobs:
  - job: snykScan
    displayName: Job - Snyk Scan
    condition: eq('${{ parameters.enabled }}', true)
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: ${{ parameters.source }}    
      - task: SnykSecurityScan@1
        displayName: Run Snyk Scan
        inputs:
          serviceConnectionEndpoint: ${{ parameters.serviceConnection }}
          testType: ${{ parameters.testType }}
          monitor: ${{ parameters.monitor }}
          projectName: ${{ parameters.projectName }}
          additionalArguments: ${{ parameters.additionalArguments }}


      {% if values.parameters.testType == 'app' %}
      - task: SnykSecurityScan@1
        inputs:
          serviceConnectionEndpoint: $(serviceConnectionEndpoint)
          testType: 'app'
          targetFile: $(targetFile)
          monitorWhen: $(monitorWhen)
          failOnIssues: $(failOnIssues)
          projectName: $(projectName)
          organization: $(organization)
          additionalArguments: $(additionalArguments)
      {% endif %}

      {% if values.parameters.testType == 'code' %}
      - task: SnykSecurityScan@1
        inputs:
          serviceConnectionEndpoint: $(serviceConnectionEndpoint)
          testType: 'code'
          failOnIssues: $(failOnIssues)
          projectName: $(projectName)
          organization: $(organization)
          additionalArguments: $(additionalArguments)
      {% endif %}

      {% if values.parameters.testType == 'container' %}
      - task: SnykSecurityScan@1
        inputs:
          serviceConnectionEndpoint: $(serviceConnectionEndpoint)
          testType: 'container'
          dockerImageName: $(dockerImageName)
          dockerfilePath: $(dockerfilePath)
          monitorWhen: $(monitorWhen)
          failOnIssues: $(failOnIssues)
          projectName: $(projectName)
          organization: $(organization)
          additionalArguments: $(additionalArguments)
      {% endif %}
