parameters:
  - name: source
    type: string
  - name: scanCode
    type: boolean
    default: false
  - name: scanCodeBackend
    type: boolean
    default: false
  - name: scanImageBackend
    type: boolean
    default: false
  - name: serviceConnectionEndpoint
    type: string
jobs:
  - job: snykScanCode
    displayName: Snyk Scan (Code)
    {% raw %}condition: eq('${{ parameters.enabled }}', true){% endraw %}
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      {% raw %}- checkout: ${{ parameters.source }}{% endraw %}
      - task: SnykSecurityScan@1
        inputs:
          {% raw %}serviceConnectionEndpoint: ${{ parameters.serviceConnectionEndpoint }}{% endraw %}
          testType: 'code'
          failOnIssues: $(failOnIssues)
          projectName: $(projectName)
          organization: $(organization)
          additionalArguments: $(additionalArguments)

  # - job: snykScanBacked
  #   displayName: Snyk Scan (Backend)
  #   {% raw %}condition: eq('${{ parameters.enabled }}', true){% endraw %}
  #   pool:
  #     vmImage: 'ubuntu-latest'
  #   steps:
  #     {% raw %}- checkout: ${{ parameters.source }}{% endraw %}
  #     {%- if values.parameters.snyKDotnetConfig.configMode == 'manual' %}
  #       - task: SnykSecurityScan@1
  #         inputs:
  #           serviceConnectionEndpoint: $(serviceConnectionEndpoint)
  #           testType: $(testType)
  #           dockerImageName: $(dockerImageName)
  #           monitorWhen: $(monitorWhen)
  #           failOnIssues: $(failOnIssues)
  #           projectName: $(projectName)
  #           organization: $(organization)
  #     {%- endif %}
