parameters:
  - name: source
    type: string
  - name: enabled
    type: boolean
    default: true
  - name: serviceConnectionEndpoint
    type: string
jobs:
  - job: snykScan
    displayName: Snyk Scan
    {% raw %}condition: eq('${{ parameters.enabled }}', true){% endraw %}
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      {% raw %}- checkout: ${{ parameters.source }}{% endraw %}
      - task: SnykSecurityScan@1
        inputs:
          {% raw %}serviceConnectionEndpoint: ${{ parameters.serviceConnectionEndpoint }}{% endraw %}
          testType: 'code'
          {%- if values.parameters.snykConfig.testType == 'app' %}
          targetFile: $(targetFile)
          monitorWhen: $(monitorWhen)
          {%- endif %}
          {%- if values.parameters.snykConfig.testType == 'container' %}
          dockerImageName: $(dockerImageName)
          dockerfilePath: $(dockerfilePath)
          monitorWhen: $(monitorWhen)
          {%- endif %}
          failOnIssues: $(failOnIssues)
          projectName: $(projectName)
          organization: $(organization)
          additionalArguments: $(additionalArguments)
     