parameters:
  - name: enabled
    type: boolean
    default: false

  - name: serviceConnection
    type: string
    default: 'snyk-service-conn'

  - name: testType
    type: string
    default: 'app'

  - name: monitor
    type: boolean
    default: false

  - name: projectName
    type: string
    default: ''

  - name: additionalArguments
    type: string
    default: ''

jobs:
  - job: snykScan
    displayName: Job - Snyk Scan
    condition: eq('${{ parameters.enabled }}', true)
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: SnykSecurityScan@1
        displayName: Run Snyk Scan
        inputs:
          serviceConnectionEndpoint: ${{ parameters.serviceConnection }}
          testType: ${{ parameters.testType }}
          monitor: ${{ parameters.monitor }}
          projectName: ${{ parameters.projectName }}
          additionalArguments: ${{ parameters.additionalArguments }}
