parameters:
  - name: imageComponents
    type: string
    default: 'frontend,backend'
  - name: tag
    type: string
    default: 'latest'
  - name: source
    type: string

jobs:
{% raw %}- ${{ each comp in split(parameters.imageComponents, ',') }}:
  - job: BuildAndScan_${{ comp }}
    displayName: Build and scan ${{ comp }}
    steps:
      - checkout: ${{ parameters.source }}
      - task: Docker@2
        displayName: "Build image: ${{ comp }}"
        inputs:
          command: 'build'
          Dockerfile: '$(Build.SourcesDirectory)/${{ comp }}/Dockerfile'
          repository: '${{ comp }}'
          tags: '${{ parameters.tag }}'
      - task: trivy@2
        inputs:
          method: $(method)
          version: $(version)
          type: image
          target: '${{ comp }}:${{ parameters.tag }}'
          scanners: $(scanners)
          severities: $(severities)
          ignoreUnfixed: $(ignoreUnfixed)
          failOnSeverityThreshold: $(failOnSeverityThreshold)
          reports: $(reports)
          publish: $(publish)
{% endraw %}
