parameters:
  - name: enabled
    type: boolean
    default: false

  - name: method
    type: string
    default: 'install'

  - name: options
    type: string
    default: ''

  - name: scanType
    type: object
    default: 'filesystem'

  - name: target
    type: string
    default: '.'

  - name: scanners
    type: object
    default:
    - 'vuln'
    values: 
    - 'vuln'
    - 'license'
    - 'misconfig'
    - 'secret'

  - name: format
    type: string
    default: 'json'

  - name: exitCode
    type: string
    default: '0'

  - name: severity
    type: string
    default: 'LOW'

  - name: dockerImage
    type: string
    default: ''

jobs:
  - job: trivyScan
    displayName: Trivy Security Scan
    condition: eq('${{ parameters.enabled }}', true)
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      formattedScanners: ${{ join(',', parameters.scanners) }}
    steps:
      - task: trivy@2
        displayName: Run Trivy Scan
        inputs:
          ${{ if eq(parameters.method, 'system') }}:
            method: system
          ${{ elseif eq(parameters.method, 'docker') }}:
            method: docker
            image: ${{ parameters.dockerImage }}
          options: ${{ parameters.options }}
          type: ${{ parameters.scanType }}
          target: ${{ parameters.target }}
          scanners: $[variables.formattedScanners]
          format: ${{ parameters.format }}
          exitCode: ${{ parameters.exitCode }}
          severity: ${{ parameters.severity }}