parameters:
  - name: source
      type: string
      default: true
  - name: enabled
      type: boolean
      default: false

jobs:
  - job: trivyScan
    displayName: Trivy Security Scan
    condition: eq('${{ parameters.enabled }}', true)
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: ${{ parameters.source }}    
      {% if values.parameters.scanType == 'filesystem' %}
        {% if values.parameters.trivyRunMethod == 'install' %}
        - task: trivy@2
          inputs:
            version: $(version)
            options: $(options)
            type: $(scanType)
            target: $(target)
            scanners: $(scanners)
            severities: $(severities)
            ignoreUnfixed: $(ignoreUnfixed)
            showSuppressed: $(showSuppressed)
            ignoreScanErrors: $(ignoreScanErrors)
            failOnSeverityThreshold: $(failOnSeverityThreshold)
            reports: $(reports)
            publish: $(publish)
        {% endif %}

        {% if values.parameters.trivyRunMethod == 'docker' %}
        - task: trivy@2
          inputs:
            method: $(method)
            image: $(image)
            version: $(version)
            options: $(options)
            type: $(scanType)
            target: $(target)
            scanners: $(scanners)
            severities: $(severities)
            ignoreUnfixed: $(ignoreUnfixed)
            showSuppressed: $(showSuppressed)
            ignoreScanErrors: $(ignoreScanErrors)
            failOnSeverityThreshold: $(failOnSeverityThreshold)
            reports: $(reports)
            publish: $(publish)
        {% endif %}

        {% if values.parameters.trivyRunMethod == 'system' %}
        - task: trivy@2
          inputs:
            method: $(method)
            options: $(options)
            type: $(scanType)
            target: $(target)
            scanners: $(scanners)
            severities: $(severities)
            ignoreUnfixed: $(ignoreUnfixed)
            showSuppressed: $(showSuppressed)
            ignoreScanErrors: $(ignoreScanErrors)
            failOnSeverityThreshold: $(failOnSeverityThreshold)
            reports: $(reports)
            publish: $(publish)
            templates: $(templates)
        {% endif %}
      {% endif %}

      {% if values.parameters.scanType == 'image' %}
        {% if values.parameters.trivyRunMethod == 'install' %}
        - task: trivy@2
          inputs:
            version: $(version)
            options: $(options)
            type: $(scanType)
            target: $(target)
            scanners: $(scanners)
            severities: $(severities)
            ignoreUnfixed: $(ignoreUnfixed)
            showSuppressed: $(showSuppressed)
            ignoreScanErrors: $(ignoreScanErrors)
            failOnSeverityThreshold: $(failOnSeverityThreshold)
            reports: $(reports)
            publish: $(publish)
        {% endif %}

        {% if values.parameters.trivyRunMethod == 'docker' %}
        - task: trivy@2
          inputs:
            method: $(method)
            image: $(image)
            version: $(version)
            options: $(options)
            type: $(scanType)
            target: $(target)
            scanners: $(scanners)
            severities: $(severities)
            ignoreUnfixed: $(ignoreUnfixed)
            showSuppressed: $(showSuppressed)
            ignoreScanErrors: $(ignoreScanErrors)
            failOnSeverityThreshold: $(failOnSeverityThreshold)
            reports: $(reports)
            publish: $(publish)
        {% endif %}

        {% if values.parameters.trivyRunMethod == 'system' %}
        - task: trivy@2
          inputs:
            method: $(method)
            options: $(options)
            type: $(scanType)
            target: $(target)
            scanners: $(scanners)
            severities: $(severities)
            ignoreUnfixed: $(ignoreUnfixed)
            showSuppressed: $(showSuppressed)
            ignoreScanErrors: $(ignoreScanErrors)
            failOnSeverityThreshold: $(failOnSeverityThreshold)
            reports: $(reports)
            publish: $(publish)
        {% endif %}
      {% endif %}

      {% if values.parameters.scanType == 'repository' %}
        {% if values.parameters.trivyRunMethod == 'install' %}
        - task: trivy@2
          inputs:
            version: $(version)
            options: $(options)
            type: $(scanType)
            target: $(target)
            scanners: $(scanners)
            severities: $(severities)
            ignoreUnfixed: $(ignoreUnfixed)
            showSuppressed: $(showSuppressed)
            ignoreScanErrors: $(ignoreScanErrors)
            failOnSeverityThreshold: $(failOnSeverityThreshold)
            reports: $(reports)
            publish: $(publish)
        {% endif %}

        {% if values.parameters.trivyRunMethod == 'docker' %}
        - task: trivy@2
          inputs:
            method: $(method)
            version: $(version)
            options: $(options)
            type: $(scanType)
            target: $(target)
            scanners: $(scanners)
            severities: $(severities)
            ignoreUnfixed: $(ignoreUnfixed)
            showSuppressed: $(showSuppressed)
            ignoreScanErrors: $(ignoreScanErrors)
            failOnSeverityThreshold: $(failOnSeverityThreshold)
            reports: $(reports)
            publish: $(publish)
        {% endif %}

        {% if values.parameters.trivyRunMethod == 'system' %}
        - task: trivy@2
          inputs:
            method: $(method)
            options: $(options)
            type: $(scanType)
            target: $(target)
            scanners: $(scanners)
            severities: $(severities)
            ignoreUnfixed: $(ignoreUnfixed)
            showSuppressed: $(showSuppressed)
            ignoreScanErrors: $(ignoreScanErrors)
            failOnSeverityThreshold: $(failOnSeverityThreshold)
            reports: $(reports)
            publish: $(publish)
        {% endif %}
      {% endif %}

      {% if values.parameters.scanType == 'sbom' %}
        {% if values.parameters.trivyRunMethod == 'install' %}
        - task: trivy@2
          inputs:
            version: $(version)
            options: $(options)
            type: $(scanType)
            target: $(target)
            scanners: $(scanners)
            severities: $(severities)
            ignoreUnfixed: $(ignoreUnfixed)
            showSuppressed: $(showSuppressed)
            ignoreScanErrors: $(ignoreScanErrors)
            failOnSeverityThreshold: $(failOnSeverityThreshold)
            reports: $(reports)
            publish: $(publish)
        {% endif %}

        {% if values.parameters.trivyRunMethod == 'docker' %}
        - task: trivy@2
          inputs:
            method: $(method)
            image: $(image)
            version: $(version)
            options: $(options)
            type: $(scanType)
            target: $(target)
            scanners: $(scanners)
            severities: $(severities)
            ignoreUnfixed: $(ignoreUnfixed)
            showSuppressed: $(showSuppressed)
            ignoreScanErrors: $(ignoreScanErrors)
            failOnSeverityThreshold: $(failOnSeverityThreshold)
            reports: $(reports)
            publish: $(publish)
        {% endif %}

        {% if values.parameters.trivyRunMethod == 'system' %}
        - task: trivy@2
          inputs:
            method: $(method)
            options: $(options)
            type: $(scanType)
            target: $(target)
            scanners: $(scanners)
            severities: $(severities)
            ignoreUnfixed: $(ignoreUnfixed)
            showSuppressed: $(showSuppressed)
            ignoreScanErrors: $(ignoreScanErrors)
            failOnSeverityThreshold: $(failOnSeverityThreshold)
            reports: $(reports)
            publish: $(publish)
            templates: $(templates)
        {% endif %}
      {% endif %}
