parameters:
  - name: source
    type: string
  - name: enabled
    type: boolean
    default: true

jobs:
  - job: trivyScan
    displayName: Trivy Scan
    {% raw %}condition: eq('${{ parameters.enabled }}', true){% endraw %}
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
      {% raw %}- checkout: ${{ parameters.source }}{% endraw %}
      - script: |
          for d in */; do
            if [ -f "$d/package.json" ]; then
              echo "📦 Installing in $d"
              npm install --prefix "$d"
            fi
          done
        displayName: 'Run a multi-line script'
      - task: trivy@2
        inputs:
          {%- if values.parameters.trivyConfig.method == 'docker' %}
          method: $(method)
          image: $(image)
          {%- endif %}
          {%- if values.parameters.trivyConfig.method == 'system' %}
          method: $(method)
          templates: $(templates)
          {%- endif %}
          version: $(version)
          options: $(options)
          type: $(type)
          target: $(target)
          scanners: $(scanners)
          severities: $(severities)
          ignoreUnfixed: $(ignoreUnfixed)
          showSuppressed: $(showSuppressed)
          ignoreScanErrors: $(ignoreScanErrors)
          failOnSeverityThreshold: $(failOnSeverityThreshold)
          reports: $(reports)
          publish: $(publish)
     
