version: "3"

services:
  # api:
  #   container_name: api
  #   build:
  #     context: .
  #     dockerfile: .
  #   volumes:
  #     - ./API/appsettings.json:/app/appsettings.json:ro
  #   restart: unless-stopped
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   ports:
  #     - 8123:8123

  database:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./Deployment/postgres/.data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_db
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./Deployment/redis/.data/db:/root/redis
      - ./Deployment/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=${REDIS_DATABASES}