apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/resource-group.yaml
  - manifests/virtual-network.yaml
  - manifests/subnet.yaml
  - manifests/aks-cluster.yaml