---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: eks-ex-cluster-role-attachment
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  providerConfigRef:
    name: aws-provider-config 
  forProvider:
    role: eks-ex-cluster-role
    policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy