apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure-management
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  package: xpkg.upbound.io/upbound/provider-azure-management:v1.7.0