name: Manage Microsoft Dev Box

on:
  workflow_dispatch:
    inputs:
      devCenterName:
        description: 'Dev Center Name'
        required: true
      projectName:
        description: 'Project name'
        required: true
      devBoxName:
        description: 'Dev Box Name'
        required: true
      region:
        description: 'Region'
        required: true
      resourceGroupName:
        description: 'Resource Group Name'
        required: true
      imageId:
        description: 'Image Id'
        required: true  
      repo:
        description: 'Repo name'
        required: true
      owner:
        description: 'owner of repo'
        required: true         
jobs:
  provision-microsoft-dev-box:
    runs-on: ubuntu-latest
    steps:
    - name: Install Azure CLI
      run: |
        sudo apt-get update
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Install DevCenter CLI extension
      run: |
        az extension add --name devcenter

    - name: Checkout Main Repository
      uses: actions/checkout@v3
    
    - name: Checkout dev box github repository 
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.owner }}/${{ github.event.inputs.repo }}  
        path: ${{ github.event.inputs.repo }} 
        token: ${{ secrets.MYGITHUB_TOKEN }}

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create parameters.json file
      run: |
        echo '{
          "devCenterName": {
            "value": "'${{ github.event.inputs.devCenterName }}'"
          },
          "region": {
            "value": "'${{ github.event.inputs.region }}'"
          },
          "projectName": {
            "value": "'${{ github.event.inputs.projectName }}'"
          },
          "imageId": {
            "value": "'/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ github.event.inputs.resourceGroupName }}/providers/Microsoft.DevCenter/devcenters/${{ github.event.inputs.devCenterName }}/galleries/default/images/${{ github.event.inputs.imageId }}'"
          },

        }' > parameters.json


    - name:  Provision Microsoft Dev Box
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
        template: './${{ github.event.inputs.repo }}/devbox.bicep' # Reference the Bicep file from the external repo
        parameters: '@parameters.json'
        deploymentMode: Incremental

    - name: Create Dev Box Pool
      run: |
        az devcenter admin pool create \
          --location ${{ github.event.inputs.region }} \
          --devbox-definition-name ${{ github.event.inputs.devCenterName }}-devboxdef \
          --pool-name ${{ github.event.inputs.devBoxName }} \
          --project-name ${{ github.event.inputs.projectName }} \
          --resource-group ${{ github.event.inputs.resourceGroupName }} \
          --local-administrator "Enabled" \
          --virtual-network-type "Managed" \
          --single-sign-on-status "Enabled" \
          --managed-virtual-network-regions ${{ github.event.inputs.region }}

    - name: Output Dev Box Details
      run: echo "Dev Box ${{ github.event.inputs.devBoxName }} provisioned in region ${{ github.event.inputs.region }}"
